var data = {
    'Pescados y Mariscos': [{
            'name': 'La Mar',
            'image': 'https://u.tfstatic.com/restaurant_photos/005/214005/169/612/la-mar-cebicheria-peruana-fachada-1d7a7.jpg',
            'distric': 'Miraflores',
            'address': 'Av. La Mar 770',
            'phone': '+51 4213365',
        }, {
            'name': 'Pescados Capitales',
            'image': 'https://www.atrapalo.pe/common/photo/res/38432/152255/ticr_0_0.jpg',
            'distric': 'Miraflores',
            'address': 'Av Mariscal La Mar 1337',
            'phone': '+51 1 4218808',
        }, {
            'name': 'Mi Barrunto',
            'image': 'https://img.peru21.pe/files/article_content_ec_fotos/uploads/2017/08/10/598cfb2643bff.jpeg',
            'distric': 'La Victoria',
            'address': 'Jr. Sebastian Barranca 940 y 935',
            'phone': '4272066',
        }, {
            'name': 'El Muelle',
            'image': 'https://media-cdn.tripadvisor.com/media/photo-s/09/d8/98/cb/20151224-172346-largejpg.jpg',
            'distric': 'Barranco',
            'address': 'Av. Alfonso Ugarte 225',
            'phone': '+51 1 2528643',
        }],
    'Criolla': [{
            'name': 'Panchita',
            'image': 'https://www.mesa247.pe/archivos/panchita/thumbs/panchita-logo_side.jpg',
            'distric': 'Lima',
            'address': 'Calle 2 de Mayo 298',
            'phone': '+51 1 2425957',
        }, {
            'name': 'Antigua Taberna Queirolo',
            'image': 'https://media-cdn.tripadvisor.com/media/photo-s/03/c5/b2/8f/antigua-taberna-queirolo.jpg',
            'distric': 'Pueblo Libre',
            'address': 'Av. San Martín 1090',
            'phone': '+51 1 4600441',
        }, {
            'name': 'El Lobby del Pardo Restaurante',
            'image': 'https://restorando-res.cloudinary.com/image/upload/s--Kua2I-Eb--/c_fit,f_auto,h_500,w_700/v1445035203/restaurant_photos/f/9547/80712/restaurante_el-lobby-del-pardo-hotel-el-pardo-doubletree-lima_miraflores_fullsizerender.jpg',
            'distric': 'Miraflores',
            'address': 'Calle Independencia 121',
            'phone': '(01) 6171000',    
        }, {
            'name': 'El Rincón que no Conoces',
            'image': 'http://4.bp.blogspot.com/_XAHB_Nvjacc/RdlL_mlSrvI/AAAAAAAAAjc/Tha_PUiPf-Q/s400/Peru+124.jpg',
            'distric': 'Lince',
            'address': 'José Bernardo Alcedo 363',
            'phone': '(01) 4712171',
        }],
    'Chifa': [{
            'name': 'Wa Lok',
            'image': 'https://www.absolutviajes.com/wp-content/uploads/2012/06/turismo-Lima1.jpg',
            'distric': 'San Miguel',
            'address': 'Av. Angamos Oeste 700',
            'phone': '(01) 4471314',
        }, {
            'name': 'Antigua Taberna Queirolo',
            'image': 'https://media-cdn.tripadvisor.com/media/photo-s/0e/67/62/6d/san-joy-lao.jpg',
            'distric': 'Lima',
            'address': 'Jr. Ucayali 779',
            'phone': '+51 1 4267799',
        }, {
            'name': 'Choy Tac',
            'image': 'https://content.emarket.pe/uploads/sites/22/2015/03/1400000016112.jpg',        
            'distric': 'Surco',
            'address': 'Avenida Alfredo Benavides Diez Canseco 3801',
            'phone': '(01) 2716847',
        }, {
            'name': 'Lung Fung',
            'image': 'http://paisanito.com/wp-content/uploads/2013/02/Restaurante-Lung-Fung-640x400.jpg',
            'distric': 'San Isidro',
            'address': 'Av. República de Panamá 3165',
            'phone': '(01) 4418817',
        }],
    'Amazónica': [{
            'name': 'El Aguajal',
            'image': 'http://3.bp.blogspot.com/-wNEXIRVjcUA/VYn5KmnxNXI/AAAAAAAAnKQ/1LoIlMIX3KE/s1600/el-aguajal.jpg',
            'distric': 'San Martin de Porres',
            'address': 'Sta Cruz de Pachacutec 155',
            'phone': '523- 6445',
        }, {
            'name': 'El Pichito',
            'image': 'https://www.atrapalo.pe/common/photo/res/15757/147586/ticr_0_0.jpg',
            'distric': 'Breña',
            'address': 'General Vidal 803',
            'phone': '956 431 314',
        }, {
            'name': 'La Choza de la Anaconda',
            'image': 'https://restorando-res.cloudinary.com/image/upload/s--L8WA2bY9--/c_fit,f_auto,h_500,w_700/v1416439498/restaurant_photos/w/6938/52867/restaurante_la-choza-de-la-anaconda_los-olivos_img-20141119-wa0016.jpg',
            'distric': 'Surco',
            'address': 'Av. Caminos del Inca 1666',
            'phone': '+51 1 2752738',
        }, {
            'name': 'El Guacamayo',
            'image': 'https://media-cdn.tripadvisor.com/media/photo-s/02/6b/96/8c/filename-30-jpg-thumbnail0.jpg',
            'distric': 'Jesús María',
            'address': 'Av Mello Franco 626',
            'phone': '(01) 4314803',
        }],
    'Vegetariana': [{
            'name': 'Bistro 400',
            'image': 'https://media-cdn.tripadvisor.com/media/photo-s/0d/84/a3/74/tea-time-at-the-bistro.jpg',
            'distric': 'Miraflores',
            'address': 'Shell 400 | Inside the Courtyard',
            'phone': '+51 1 6253838',
        }, {
            'name': 'Rigoletto Lima',
            'image': 'https://media-cdn.tripadvisor.com/media/photo-s/07/58/28/2f/restaurante-rigoletto.jpg',
            'distric': 'Lima',
            'address': 'Calle Colón 161',
            'phone': '+51 981 483 975',
        }, {
            'name': 'Germinando Vida',
            'image': 'https://i2.wp.com/www.todovegano.com/wp-content/uploads/2015/08/Germinando-Vida.png2_.jpg?resize=823%2C420',
            'distric': 'Barranco',
            'address': 'Avenida Grau 209-A',
            'phone': '+51 937 040 006',
        }, {
            'name': 'Veggie Pizza',
            'image': 'https://media-cdn.tripadvisor.com/media/photo-s/07/5a/f7/86/veggie-pizza-peru.jpg',
            'distric': 'Lima',
            'address': 'Jirón Colina 112',
            'phone': '+51 1 2475963',
        }],